language: c++

addons:
  apt:
    packages: lcov

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11

install:
  - bash bootstrap

script:
  - . ~/.bashrc
  - mkdir build
  - pushd build
  - cmake ../
  - make
  - echo running unit tests...
  - ./test/unit/unit_tests
  - ./test/unit/types/types_test
  - echo running system tests...
  - popd
  - pushd rtlib
  - ./build.sh
  - popd
  - pushd test/system
  - ./run.sh
  - popd 

after_success:
  - lcov --capture --directory build/src -output-file coverage.info
  - lcov --remove coverage.info '/usr/include/*' -o coverage.info
  - lcov --remove coverage.info '*.h' -o coverage.info
  - lcov --remove coverage.info '*.def' -o coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
