language: c++

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

install:
  - bash bootstrap

script:
  - . ~/.bashrc
  - mkdir build
  - cd build
  - cmake ../
  - make
  - echo running unit tests...
  - ./test/unit/unit_tests
